stages:
  - test
  - build

.docker_login:
  image: docker:18.09
  services:
    - docker:18.09-dind
  before_script:
    - echo "$DOCKER_REGISTRY_PASS" | docker login --username $DOCKER_REGISTRY_USER --password-stdin

build_bot:
  extends: .docker_login
  stage: build
  script:
    - echo 'Building docker image crawler'
    - docker info
    - docker build -t $DOCKER_REGISTRY_USER/crawler docker/crawler
    - docker push $DOCKER_REGISTRY_USER/crawler

build_ui:
  extends: .docker_login
  stage: build
  script:
    - echo 'Building docker image crawler_ui'
    - docker info
    - docker build -t $DOCKER_REGISTRY_USER/crawler_ui docker/ui
    - docker push $DOCKER_REGISTRY_USER/crawler_ui

test_bot:
  stage: test
  image: python:3.6.0-alpine
  services:
    - rabbitmq:3-management-alpine
  variables:
    RMQ_HOST: rabbitmq
    RMQ_QUEUE: 5672
    RMQ_USERNAME: guest
    RMQ_PASSWORD: guest
  script:
    - apk --no-cache --update add git
    - git clone https://github.com/express42/search_engine_crawler.git /app
    - pip install -r /app/requirements.txt -r /app/requirements-test.txt
    - python -m unittest discover -s tests/
    - coverage run -m unittest discover -s tests/
    - coverage report --include crawler/crawler.py

test_ui:
  stage: test
  image: python:3.6.0-alpine
  script:
    - apk --no-cache --update add git
    - git clone https://github.com/express42/search_engine_ui.git /app /app
    - pip install -r /app/requirements.txt -r /app/requirements-test.txt
    - python -m unittest discover -s tests/
    - coverage run -m unittest discover -s tests/
    - coverage report --include ui/ui.py
