global:
  slack_api_url: 'https://hooks.slack.com/services/TOKEN'

route:
  receiver: "slack-notifications"
  routes:
    - match:
        severity: info
      receiver: "email"
    - match:
        severity: page
      receiver: "slack-notifications"

receivers:
  - name: "slack-notifications"
    slack_configs:
      - send_resolved: true
        #channel: <channel>#
        #api_url: <url>#

  - name: "email"
    email_configs:
      - to: "receiver_mail_id@gmail.com"
        from: "mail_id@gmail.com"
        smarthost: smtp.gmail.com:587
        auth_username: "mail_id@gmail.com"
        auth_identity: "mail_id@gmail.com"
        auth_password: "password"
