# spec:
#   containers:
#     - name: crawler
#       image: barmank32/crawler:1.0
#       tty: false
#       stdin: false
#       env:
#         - name: MONGO
#           value: mongo-db
#         - name: RMQ_HOST
#           value: rabbitmq
#         - name: RMQ_USERNAME
#           value: rabbitmq_user
#         - name: RMQ_PASSWORD
#           value: rabbitmq_pass
#   restartPolicy: Always
---
version: "3.7"
services:
  crawler:
    image: barmank32/crawler:1.0
    environment:
      MONGO: mongo-db
      RMQ_HOST:  rabbitmq
      RMQ_USERNAME: rabbitmq_user
      RMQ_PASSWORD: rabbitmq_pass
    logging:
      driver: "fluentd"
      options: 
        fluentd-async-connect: "true"
        fluentd-address: loging:24224
        tag: "crawler"
    restart: always