version: "3.7"
services:
  # prometheus:
  #   image: prom/prometheus:v2.25.0
  #   ports:
  #     - "9090:9090"
  #   volumes:
  #     - type: bind
  #       source: ./prometheus/prometheus.yml
  #       target: /etc/prometheus/prometheus.yml
  #     - type: bind
  #       source: ./prometheus/alert.rules.yml
  #       target: /etc/prometheus/alert.rules.yml
  #     - prometheus_data:/prometheus
  #   command:
  #     - "--config.file=/etc/prometheus/prometheus.yml"
  #     - "--storage.tsdb.path=/prometheus"
  #     - "--storage.tsdb.retention=7d"
  #     - "--web.enable-lifecycle"
  #   restart: always
  # blackbox-exporter:
  #   image: prom/blackbox-exporter
  #   volumes:
  #     - type: bind
  #       source: ./blackbox-exporter/config.yml
  #       target: /etc/blackboxexporter/config.yml
  #   command:
  #     - "--config.file=/etc/blackboxexporter/config.yml"
  #   restart: always
  grafana:
    image: grafana/grafana:7.4.3
    ports:
      - 3000:3000
    user: "472:1"
    volumes:
      - /mnt/grafana_data:/var/lib/grafana
    restart: always
  # alertmanager:
  #   image: prom/alertmanager:v0.21.0
  #   ports:
  #     - 9093:9093
  #   volumes:
  #     - type: bind
  #       source: ./alertmanager/alertmanager.yml
  #       target: /etc/alertmanager/alertmanager.yml
  #   restart: always

x-yc-disks:
  - device_name: compute-disk-data
    fs_type: ext4
    host_path: /mnt/grafana_data
    partition: 1
  # - device_name: compute-disk-data
  #   fs_type: ext4
  #   host_path: /mnt/logs
  #   partition: 2

