FROM crawler:latest

RUN pip install -r /app/requirements-test.txt

WORKDIR /app
CMD python -m unittest discover -s tests/ ;\
    coverage run -m unittest discover -s tests/ ;\
    coverage report --include crawler/crawler.py
