version: "3.3"
services:
  mongo_db:
    image: mongo:3.2
    ports:
      - 27017:27017
    volumes:
      - mongo_db:/data/db
  rabbitmq:
    image: rabbitmq:3-management-alpine
    ports:
      - 8080:15672
      - 5672:5672
    environment:
      - RABBITMQ_DEFAULT_USER=rabbitmq_user
      - RABBITMQ_DEFAULT_PASS=rabbitmq_pass
  ui:
    image: ${USERNAME}/crawler_ui:1.0
    ports:
      - 8000:8000
    environment:
      - MONGO=mongo_db
      - MONGO_PORT=27017
    depends_on:
      - mongo_db
  crawler:
    image: ${USERNAME}/crawler:1.0
    restart: always
    environment:
      - MONGO=mongo_db
      - MONGO_PORT=27017
      - RMQ_HOST=rabbitmq
      - RMQ_QUEUE=5672
      - RMQ_USERNAME=rabbitmq_user
      - RMQ_PASSWORD=rabbitmq_pass
    depends_on:
      - mongo_db
      - rabbitmq
  nginx:
    image: nginx:1.19-alpine
    restart: always
    ports:
    - "80:80"
    volumes:
    - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - ui
volumes:
  mongo_db:
