FROM crawler_ui:latest

RUN pip install -r /app/requirements-test.txt

WORKDIR /app
EXPOSE 8000

CMD python -m unittest discover -s tests/ ; coverage run -m unittest discover -s tests/ ; coverage report --include ui/ui.py
