{
 "title": "Dashboard",
 "time": { "from": "now-3h", "to": "now" },
 "panels": [
  {
   "title": "Web page gen time sum",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum (rate (web_page_gen_time_sum[1m]))"
    }
   ]
  },
  {
   "title": "Web page gen time count",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum (rate (web_page_gen_time_count[1m]))"
    }
   ]
  },
  {
   "title": "Web page gen time bucket",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum (rate (web_page_gen_time_bucket[1m]))"
    }
   ]
  },
  {
   "title": "Web pages served",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum (rate (web_pages_served[1m]))"
    }
   ]
  },
  {
   "title": "Crawler page parse_time sum",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum (rate (crawler_page_parse_time_sum[1m]))"
    }
   ]
  },
  {
   "title": "Crawler page parse time count",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum (rate (crawler_page_parse_time_count[1m]))"
    }
   ]
  },
  {
   "title": "Crawler page parse time bucket",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 24 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum (rate (crawler_page_parse_time_bucket[1m]))"
    }
   ]
  },
  {
   "title": "Crawler site connection time sum",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 24 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum (rate (crawler_site_connection_time_sum[1m]))"
    }
   ]
  },
  {
   "title": "Crawler site connection time count",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 32 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum (rate (crawler_site_connection_time_count[1m]))"
    }
   ]
  },
  {
   "title": "Crawler site connection time bucket",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 32 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum (rate (crawler_site_connection_time_bucket[1m]))"
    }
   ]
  },
  {
   "title": "Crawler pages parsed (1m)",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 40 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum (rate (crawler_pages_parsed[1m]))"
    }
   ]
  }
 ]
}